spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./spdb/${server.port}
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  profiles:
    include: security
